/* This file was generated by syncqt. */
#ifndef QT_QTPDFQUICK_VERSION_H
#define QT_QTPDFQUICK_VERSION_H

#define QTPDFQUICK_VERSION_STR "6.4.3"

#define QTPDFQUICK_VERSION 0x060403

#endif // QT_QTPDFQUICK_VERSION_H
